// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6YOn-qomJBC996ZezP-JIMzNWdCy6mR8',
    appId: '1:374669470820:web:6f6963f31923bd1b620371',
    messagingSenderId: '374669470820',
    projectId: 'fir-series-93e7b',
    authDomain: 'fir-series-93e7b.firebaseapp.com',
    storageBucket: 'fir-series-93e7b.firebasestorage.app',
    measurementId: 'G-WGQS7CVTKB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYuCh9bJeE180ON4XvYQ53Zvx-d_GwnQE',
    appId: '1:374669470820:android:271119ce8fc41331620371',
    messagingSenderId: '374669470820',
    projectId: 'fir-series-93e7b',
    storageBucket: 'fir-series-93e7b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqe7Vuuy8GCf3lSDI4cmnbwB9FQ7xOioU',
    appId: '1:374669470820:ios:aee298df8a30af8d620371',
    messagingSenderId: '374669470820',
    projectId: 'fir-series-93e7b',
    storageBucket: 'fir-series-93e7b.firebasestorage.app',
    iosBundleId: 'com.example.shophop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqe7Vuuy8GCf3lSDI4cmnbwB9FQ7xOioU',
    appId: '1:374669470820:ios:aee298df8a30af8d620371',
    messagingSenderId: '374669470820',
    projectId: 'fir-series-93e7b',
    storageBucket: 'fir-series-93e7b.firebasestorage.app',
    iosBundleId: 'com.example.shophop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6YOn-qomJBC996ZezP-JIMzNWdCy6mR8',
    appId: '1:374669470820:web:8f5be3d87827e875620371',
    messagingSenderId: '374669470820',
    projectId: 'fir-series-93e7b',
    authDomain: 'fir-series-93e7b.firebaseapp.com',
    storageBucket: 'fir-series-93e7b.firebasestorage.app',
    measurementId: 'G-Y8P4TB3KFL',
  );
}
